[build]
  command = "pnpm run build"
  publish = "apps/blog/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  condition = { Role = ["admin"] } # dummy to show toml config, Netlify handles static nicely 
